### ISSUE TITLE
Informational only: "docker run hello-world"

### ISSUE THREAD

**Issue by falkobanaszak** [IBM/spectrum-protect-sppmon#12]
If possible you can add **"su -s ${USER}"** to the guide on installing SPPMon within a docker environment after adding the user to the docker group. Normally you would need to log off and on again to evaluate the group again or use the above command.

[sppmon@localhost ~]$ docker run hello-world
/usr/bin/docker-current: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See '/usr/bin/docker-current run --help'.

**Comment by baslerj** [comment]
Thanks for the suggestion.  I have update the instructions with `su - ${USER}` omitting the -s which did not work on  my system.

**Comment by NielsKorschinsky** [comment]
I'm closing this issue since it seems like everything is resolved. 
Feel free to reopen if there are any further questions or issues.
