### ISSUE TITLE
ssh call parser issue with not numberic  in methods_util.py

### ISSUE THREAD

**Issue by DominicMW** [IBM/spectrum-protect-sppmon#14]
#  /usr/bin/python3.8 /root/git/spectrum-protect-sppmon-0.3beta/python/sppmon.py --cfg=/root/git/spectrum-protect-sppmon-0.3beta/config_files/sppconnections_default.conf --hourly

...

>> executing ssh commands, which are labled to be executed for OTHER ssh clients
> executing process_stats ssh commands
Error when parsing result, skipping parsing of this result
Exception in FILE: methods_utils.py, Line: 90, Exception: <class 'ValueError'>
Exception Message: value is not numeric
Exception args: ('13123705+total,',)
Error when parsing result, skipping parsing of this result
Exception in FILE: methods_utils.py, Line: 90, Exception: <class 'ValueError'>
Exception Message: value is not numeric
Exception args: ('13123705+total,',)
Error when parsing result, skipping parsing of this result
Exception in FILE: methods_utils.py, Line: 90, Exception: <class 'ValueError'>
Exception Message: value is not numeric
Exception args: ('13123705+total,',)
> getting vadps
> getting storages
>> inserting storage info into database
Storing script metrics
total of 9 exception/s occured
Stored script metrics sucessfull

**Comment by NielsKorschinsky** [comment]
Hello @DominicMW,

A few questions about this error:
1. What kind of `other` client were you requesting? What is the OS of that system?
2. Did this issue occur another time? Can you reproduce it? 
3. If neither of the points above are true: Do you still have the logfile of any of those errors?

I'd like to check and debug this error with live data. It seems to me like the format of any ssh-command did change. I have to manually adjust the ssh-command-parsing.

**Comment by DominicMW** [comment]
Hi @NielsKorschinsky , the problem was reported from a customer. I will ask him for more detailed information of examples of the ssh calls/responses from the machines he added.

**Comment by NielsKorschinsky** [comment]
Thanks Dominic!

The error occured most likley on the SPP-Server (or the ssh-client labeled as `SERVER`).
I need two steps of verification, where the first one is the most important. Only execute the second one if the same error did occur again.

1. Step: Execute SPPMon with the `--verbose`, `--processStats` and `--debug` simultanously. If an error is thrown, I need the log file (Result of following command, printed at end of SPPMon):
`check log for details: grep "PID XXXX" C:\Path\to\log\sppserver.log > sppmon.log.XXXX`
> Please attach it as a file since it will be bigger.

2. If a error is thrown in step 1, you will see just above it on which client it did occur. This should be the host-address of your SPP-Server. **If not, make sure only your spp-server is labled as `SERVER`**.

Please do manually log in into this system and execute the following commands. I need a full copy of the terminal output.
`mpstat`
`free`
`top -b -n1 -p $(pgrep -d',' -f mongod)`
`top -b -n1 -p $(pgrep -d',' -f beam.smp)`
`top -b -n1 -p $(pgrep -d',' -f java)`

**Comment by DominicMW** [comment]
I asked the customer for this information.
