### ISSUE TITLE
Improve M365 monitoring

### ISSUE THREAD

**Issue by DominicMW** [IBM/spectrum-protect-sppmon#22]
The monitoring for M365 should be improved. It would be helpful to have the below information:
- accounts per tenant (most likely there is only one tenant)
- objects per job (success / fail)
- transfer size per category

Here some helpful messages:

One message per job:
CTGGR0003 | [node200.kelsterbach.de.ibm.com] Successfully imported Microsoft 365 users: 17
CTGGA2440 | Total mailboxe(s)/contact(s)/calendar(s)/onedrive(s) selected in this job 51
CTGGA2444 | Total number of mailboxe(s)/contact(s)/calendar(s)/onedrive(s) protected by this job:51/51
CTGGA0804 | Protection task 2 completed in 6 min(s) 33 sec(s) and ended with status COMPLETED.

This message comes for each account for each object. Maybe we can sum up the transfer size for each category?:
CTGGA2402 | 0815dev ==> Mailbox (Server: node200.kelsterbach.de.ibm.com, Transfer Size: 0.0 B)
CTGGA2402 | 0815dev ==> Calendars (Server: node200.kelsterbach.de.ibm.com, Transfer Size: 0.0 B)
CTGGA2402 | 0815dev ==> Contacts (Server: node200.kelsterbach.de.ibm.com, Transfer Size: 0.0 B)
CTGGA2402 | 0815dev ==> OneDrive (Server: node200.kelsterbach.de.ibm.com, Transfer Size: 0.0 B)

**Comment by NielsKorschinsky** [comment]
Thanks for your patience, I've Implemented this now, see Pull-Request #33 .
- Parsed Message ID `CTGGR0003` and `CTGGA2444` into the new Table `office365Stats`.
This also includes additional information like `jobId`, `JopbSessionId` and `JobName` for optional cross-referencing to the `jobs`-table.

- Ignored MessageId `CTGGA2440 ` due redundancy with id `CTGGA2444`. 
- Ignored MessageId `CTGGA0804` due redundancy with `jobs` table. 

- The messageId `CTGGA2402` is a little bit of an issue: It is used for multiple jobs, not only this kind. 
To be concrete, it is used by at least by the following ones in addition to Office365.
  - `MongoDB`: `name Connection: 'name:port' ==>  [ALL] ` Sometimes there is also an `ALL(type: name, Transfer Size 0.0B)`-Part.
  - `fileSystem`: `name ==> [List, of, Things]`
  - `SQL`: `name ==> [list, with, databases]`
 Therefore I am now parsing for the `Transfer Size 0.0B` string and whether it is `Calendars`, `Mailbox` or others. This is highly depentent on localiszation and format of the string.
 I am unable to make a difference here between the MongoDB and Office365 stats, therefore I've also inserted the job information for manual filtering. 
 
 @DominicMW Does that fulfill your request? Do you have any other notes?

**Comment by DominicMW** [comment]
Hi @NielsKorschinsky , my environment is not running at this time. I will verify the changes as soon as possible. Thanks for the implementation. - Dominic.

**Comment by NielsKorschinsky** [comment]
I'm closing this since the pull request has been merged. If you have any questions or notes, please feel free to re-open.
