### ISSUE TITLE
collection of dashboard issues

### ISSUE THREAD

**Issue by baslerj** [IBM/spectrum-protect-sppmon#27]
Creating this issue to collect minor dashboard issues that need to be corrected

- [ ] vSnap _Site Storage Used (by capacity)_ chart is showing an average rather than sum of all vSnaps in the site.  Also, after adjusting to a sum, we see there is double-counting on days that --all runs showing an invalid spike in use.
- [ ] Increase thickness of "Success Ratio" line in backup success chart so it stands out more.
- [ ] Reduce alert threshold for _vSnap Storage Used (by percent)_.  Usage of vSnap above 80% is critical, so we should alert prior to that.

**Comment by NielsKorschinsky** [comment]
1. Edited, changed to a Sub-Query first calculating the mean of each sub-storage, then summing up into the total site storage used.
2. Increased from 1 to 4
3. Reduced to 65% to have some buffer to the 80% line

**Comment by NielsKorschinsky** [comment]
Also disabled max val on the CPU TOP Server panel.
Bugfixed multiple 90/INF TOP-Command panels.
