### ISSUE TITLE
The InfluxDB version panel is incomplete unless an admin influx user is used

### ISSUE THREAD

**Issue by baslerj** [IBM/spectrum-protect-sppmon#4]
The SPPmon setup instructions recommend using the grafanaReader user to register Influx as a data source.  This prevents the InfluxDB version from determining the version and it reports "No Data".

The explanation includes:
`InfluxDB Error: error authorizing query: grafanaReader not authorized to execute statement 'SHOW DIAGNOSTICS', requires admin privilege`

Need to find an alternate source of the Influx version that does not require admin privileges.

**Comment by nkrs44** [comment]
Apparently to this issue, the version is send with each request. Maybe Grafana is able to read it, though I am not sure if the display of request information is supported.

https://github.com/influxdata/influxdb/issues/1072
