### ISSUE TITLE
Research and document minimum user roles required for the sppmon user into the SPP UI

### ISSUE THREAD

**Issue by baslerj** [IBM/spectrum-protect-sppmon#5]
The setup instruction currently require the sppmon user to SPP to have sysadmin authority.  We need to identify the minimum privileges required and update the wiki with instructions on how to setup a RBAC role in the SPP UI with restricted privileges for SPPmon.

**Comment by nkrs44** [comment]
It would also be very beficial, if the steps to setup a user on each ssh-client, are described more accuratly, as well as an explanation which users are required. Most of the requests were caused due a misunderstanding whether you need a single account on each ssh-client or not.

**Comment by baslerj** [comment]
I have updated the following page in the wiki to provide instructions for creating a restricted monitoring role and assigning this role to the user created for SPPmon REST API queries.  Testing confirms SPPmon continues to operate successfully when assigned to this restricted user.
https://github.com/IBM/spectrum-protect-sppmon/wiki/Create-user-accounts-in-SPP-server-and-vsnaps
