### ISSUE TITLE
Error during first run of sppmon.py

### ISSUE THREAD

**Issue by JCooley78** [IBM/spectrum-protect-sppmon#50]
Hello.  I have followed the install steps for SPPMON and am at the point where I need to run the sppmon.py script for the first time.  When I execute it I get the following:
[root@ ~]# /usr/bin/python3.8 /sppmon_schedule_files/sppmon.py --cfg=/sppmon_schedule_files/sppserver1.conf --all
Traceback (most recent call last):
  File "/sppmon_schedule_files/sppmon.py", line 67, in <module>
    from influx.influx_client import InfluxClient
ModuleNotFoundError: No module named 'influx'

What step or process could I have missed to cause this?  Thank you in advance.

**Comment by NielsKorschinsky** [comment]
Hello @JCooley78 ,

It seems like you skipped the `SPPMON Packages` in the Wiki. 
Make sure to have every step resolved on this page, especially the install of all dependencies:
```pip3.8 install -r sppmon/python/requirements.txt```

If the problem still exists, please feel free to comment again.

**Comment by JCooley78** [comment]
Hello.  I did run that command earlier.  Here is the output I received:
pip3.8 install -r sppmon/python/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'sppmon/python/requirements.txt

I searched for the requirements.txt file and found it here: /root/git/spectrum-protect-sppmon/python/requirements.txt
I then ran "pip3.8 install -r /root/git/spectrum-protect-sppmon/python/requirements.txt" and this is the resulting output:

[root@lbssppmon1 git]# pip3.8 install -r spectrum-protect-sppmon/python/requirements.txt
Requirement already satisfied: bcrypt==3.1.7 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 1)) (3.1.7)
Requirement already satisfied: certifi==2020.4.5.1 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 2)) (2020.4.5.1)
Requirement already satisfied: cffi==1.14.0 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: cryptography==2.9.2 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 5)) (2.9.2)
Requirement already satisfied: idna==2.9 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 6)) (2.9)
Requirement already satisfied: influxdb==5.3.0 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 7)) (5.3.0)
Requirement already satisfied: msgpack==0.6.1 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 8)) (0.6.1)
Requirement already satisfied: paramiko==2.7.1 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 9)) (2.7.1)
Requirement already satisfied: prettytable==0.7.2 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 10)) (0.7.2)
Requirement already satisfied: pycparser==2.20 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 11)) (2.20)
Requirement already satisfied: PyNaCl==1.3.0 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 12)) (1.3.0)
Requirement already satisfied: python-dateutil==2.8.1 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 13)) (2.8.1)
Requirement already satisfied: pytz==2020.1 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 14)) (2020.1)
Requirement already satisfied: requests==2.23.0 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 15)) (2.23.0)
Requirement already satisfied: six==1.14.0 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 16)) (1.14.0)
Requirement already satisfied: urllib3==1.25.9 in /usr/lib/python3.8/site-packages (from -r spectrum-protect-sppmon/python/requirements.txt (line 17)) (1.25.9)
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by JCooley78** [comment]
However, even after rerunning the above I still get the following:
[root@lbssppmon1 sppmon_schedule_files]# cd /
[root@lbssppmon1 /]# /usr/bin/python3.8 /sppmon_schedule_files/sppmon.py --cfg=/sppmon_schedule_files/sppserver1.conf --all
Traceback (most recent call last):
  File "/sppmon_schedule_files/sppmon.py", line 67, in <module>
    from influx.influx_client import InfluxClient
ModuleNotFoundError: No module named 'influx'

**Comment by NielsKorschinsky** [comment]
Thanks for beeing so patience & sorry for the late response. I'm back now to work.

I've adjusted the wiki for the new path of the requirements file.

It still seems like the influxdb module is missing.
You may try `pip3.8 install influxdb==5.3.0` to manually force an install even if it is already installed.
If this still does not work please comment again and I will try to look into this togehter with you.

**Comment by JCooley78** [comment]
Hello.  Thank you for getting back to me. I ran the install command. Here is the output:
[root@ ~]# pip3.8 install influxdb==5.3.0
Requirement already satisfied: influxdb==5.3.0 in /usr/lib/python3.8/site-packages (5.3.0)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/lib/python3.8/site-packages (from influxdb==5.3.0) (2.8.1)
Requirement already satisfied: msgpack==0.6.1 in /usr/lib/python3.8/site-packages (from influxdb==5.3.0) (0.6.1)
Requirement already satisfied: pytz in /usr/lib/python3.8/site-packages (from influxdb==5.3.0) (2020.1)
Requirement already satisfied: requests>=2.17.0 in /usr/lib/python3.8/site-packages (from influxdb==5.3.0) (2.23.0)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.8/site-packages (from influxdb==5.3.0) (1.14.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.17.0->influxdb==5.3.0) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests>=2.17.0->influxdb==5.3.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests>=2.17.0->influxdb==5.3.0) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages(from requests>=2.17.0->influxdb==5.3.0) (2.9)
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I then re-ran sppmon.py command to see if anything updated.  Here is the output:
[root@ ~]# /usr/bin/python3.8 /sppmon_schedule_files/sppmon.py --cfg=/sppmon_schedule_files/sppserver1.conf --all
Traceback (most recent call last):
  File "/sppmon_schedule_files/sppmon.py", line 67, in <module>
    from influx.influx_client import InfluxClient
ModuleNotFoundError: No module named 'influx'

What would you recommend next?  Thanks!

**Comment by NielsKorschinsky** [comment]
To be honest, I'm really not sure why it is not working. My last guess would be that the dependency is corrupted - a reinstall of the module should be useful.
Try: `pip3.8 install --upgrade --force-reinstall --no-deps --no-cache-dir influxdb==5.3.0`
If that works but other modules dont, you can maybe reinstall the whole requirements file.

**Comment by JCooley78** [comment]
Still getting the same message:
[root@~]# /usr/bin/python3.8 /sppmon_schedule_files/sppmon.py --cfg=/sppmon_schedule_files/sppserver1.conf --all
Traceback (most recent call last):
  File "/sppmon_schedule_files/sppmon.py", line 67, in <module>
    from influx.influx_client import InfluxClient
ModuleNotFoundError: No module named 'influx'

Is there a process to uninstall the components?  I can remove everything and start over to see if the issue persists.

**Comment by NielsKorschinsky** [comment]
Thats sad to hear.

You can may uninstall all requirements via `pip3.8 uninstall -r requirements.txt`
You may also uninstall python 3.8 (in case the folder still exists) by:
``` 
cd /tmp/python382/Python-3.8.2
sudo make uninstall
```

Be aware that I am not able to test these steps.

**Comment by NielsKorschinsky** [comment]
Can you please post the output of:
`which pip3.8` and `which python3.8`

I'm currently writing an install script - I hope your isssue is going to be obsolete in future, although that might not fix your actual issue.

**Comment by JCooley78** [comment]
Here is the output you requested:
[root@ ~]# which pip3.8
/usr/bin/pip3.8
[root@ ~]# which python3.8
/usr/bin/python3.8

**Comment by baslerj** [comment]
@JCooley78 I would like to explore another possible explanation.  I am able to produce the same error when I copy sppmon.py to another path location where the influx modules are not present in the same directory.  I see in your example you are invoking sppmon.py from the location _/sppmon_schedule_files/sppmon.py_.   Under a typical extract of the code, sppmon.py would be located under a folder named python and the influx module files under a folder named influx that exists in the same directory as sppmon.py.  Can you please confirm the code structure that exists under sppmon_schedule_files.

**Comment by JCooley78** [comment]
@baslerj That was the issue.  I reran the command with the native locations of the sppmon.py and the sppserver1.conf files and was able to have the script complete.  Thank you!
