### ISSUE TITLE
SPP MON configuraiton

### ISSUE THREAD

**Issue by sonukumarsahu1987** [IBM/spectrum-protect-sppmon#61]
We are in process of SPP MON configuration and we don't have internet in linux machine. Is there any other manual way to proceed further with the steps. We are on below steps.

Authorize this system to access your github account via the ssh key

    Navigate to Settings -> SSH and GPG keys
    Enter the content of id_git.pub to your github account.

Setup the git connection

sudo mkdir /root/git
cd /root/git
git init
Initialized empty Git repository in /root/git/.git/
git config --global user.email "YourName@mail.com"
git config --global user.name "Your Name"

git config core.sshCommand 'ssh -i /root/.ssh/id_rsa'
**ssh -T git@github.com**
Hi Your Name! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by NielsKorschinsky** [comment]
Without internet you do not need to clone it, but rather copy it from a system which has internet. 
Make sure to copy the whole `spectrum-protect-sppmon` folder.
Be aware to recieve updates you have to replace the changed files manually.

You may also clone via HTTPS, this should prevent the requirement to config a user:
`git clone https://github.com/IBM/spectrum-protect-sppmon.git`

**Comment by NielsKorschinsky** [comment]
I've updated the install instructions to also represent https-cloning

**Comment by NielsKorschinsky** [comment]
We've had a personal meeting which resolved any issues within this installation process. 
I've updated some of the cloning website in the meanwhile to better represent this step.
Main Issues which remain are the upgrade of the containered version to influx 2.0, as well as the install script which is upcoming in version SPPMon 1.0 which will shorten the install process.
I'm closing this, if you have any further questions or comments feel free to re-open.
