### ISSUE TITLE
Are multiple vSnaps and VADPs entries supported in the config file?

### ISSUE THREAD

**Issue by scheffczyk** [IBM/spectrum-protect-sppmon#85]
Hello,
I'm trying to set up the containerized version of sppmon.
I get an error when testing the setup if multiple vsnaps and/or VADPs are configured in the config file.
With only one vsnap and VADP everything works fine.
Are multiple vsnaps and VADPs not supported?
The error is:

Starting SPPMon
Setting up configurations
> WARNING: An option for a utility operation has been specified.  Bypassing normal SPPMON operation.
Starting argument execution
Testing all connections required for SPPMon to work
> Testing and configuring InfluxDB

Tested InfluxDB sucessfully. Ready for use
> Testing REST-API of SPP.
>> Sucessfully connected to SPP V10.1.9, build 2652.
> REST-API is ready for use

> Testing all types of SSH-Clients: Server, VAPDs, vSnaps, Cloudproxy and others
Exception in FILE: sppmon.py, Line: 915, Exception: <class 'KeyError'>
Exception Message: VSNAP
Top-level-error when testing connection.
check log for details: grep "PID 1" /root/sppmonLogs/SPPvhrz803.log > sppmon.log.1

Thanks and kind regards, Christian

**Comment by NielsKorschinsky** [comment]
Hello Christian,

Multiple vsnaps and vadps are supported and encouraged, only by adding all vsnaps/vadp full status informations are available.

Which version of SPPMon are you using? 
We've had a similar error some time ago when using the `--test` function, while the regular execution was performing well. 
This should be fixed with the current live version, if not - please send me the logs per mail ([niels.korschinsky2@ibm.com](mailto:niels.korschinsky2@ibm.com)):
> `check log for details: grep "PID 1" /root/sppmonLogs/SPPvhrz803.log > sppmon.log.1`

**Comment by NielsKorschinsky** [comment]
This is an bug fixed in the dev-version of SPPMon. We will try to release this version soon, together with other bugfixes.

**Comment by scheffczyk** [comment]
Hello Niels,
sorry for the delay, I'm busy with a lot of tickets with IBM with respect
to SPP. ;-)
It's fine to hear that multiple vsnaps/vadp are supported.
I'm running the latest stable version 1.0.1.
I only checked indeed with the --test flag.
Because of the failure I'm running the production with one vsnap only at
the moment.
What do you mean by "live version"? master, develop, something else ?
Are you still interested in the logs?

Another question. Are you collecting different metrics for the vsnaps and
vadps via ssh?
I have four vsnaps installed on VMs and on every VM runs one vsnap and one
vadp.
Should I add an entry for all vsnaps and vadps in the config file or is it
sufficient to add
the vsnaps only because they are running on the same VM as the vadps?

Hint: I think there is a typo in the docs, on page
https://github.com/IBM/spectrum-protect-sppmon/wiki/Creating-a-sppmon.conf-file
in the section for *InfluxDBin *the second line

   - username - string: name of the user to be logged in into the InfluxDB.
   Use GrafanaReader.

The user should be the influxADmin, not the GrafanaReader, correct?
At least for me it works only with the influxAdmin.

Thanks and kind regards, Christian

Am Do., 17. Feb. 2022 um 11:18 Uhr schrieb Niels Korschinsky <
***@***.***>:
